### ISSUE TITLE
Не рабочий пример

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#122]
Здесь у вас последняя версия стоит, очень много глюков.
http://www.oknosoft.ru/assets/examples/unf/

**Comment by unpete** [comment]
Версия в _assets/examples/_ от декабря 2015 v0.9.206
Пример почти без кода. Там единственный обработчик события при редактировании строки в документе _Заказ_
Актуальная metadata.js не использует прямое обращение к 1С. Основное серверное хранилище - CouchDB. Пример _assets/examples/unf/_ иллюстрирует прямую работу с 1С.
Перевести на русский язык фразу "очень много глюков" затрудняюсь.
Пришлите, пожалуйста код тестов, воспроизводящих проблему.

**Comment by kodermax** [comment]
Не работает добавление заказа покупателя
![image](https://cloud.githubusercontent.com/assets/590985/17017949/33d7b9ac-4f3e-11e6-8f1e-6f65f4d7b7fa.png)

**Comment by unpete** [comment]
> Не работает добавление заказа покупателя

Проблема на стороне 1с, а не  metadata.js. Скорее всего, у пользователя _Дилер_ просто нет прав на добавление заказов.

Если у вас есть живая задача, под которую рассматриваете возможность использовать metadata.js, предлагаю создать общий репозиторий и демо-стенд.
Metadata предлагает совершенно новую концепцию разработки веб-приложений.
Самостоятельно разобраться трудно. Опыт react, angular и .net не поможет. Но решенная в 20 строк ваша реальная задача, очень ускорит понимание идеологии.

**Comment by kodermax** [comment]
Да есть живая задача, сделать заявку на закупку.
Что от меня требуется?

**Comment by unpete** [comment]
- Заявка должна появиться в 1С? Если да, то какая типовая будет использоваться
- Нужен ли гостевой режим или все пользователи являются сотрудниками или дилерами
- Нужен ли offline
- Нужны ли какие либо вычисления внутри заказа (индивидуальные скидки, расчет параметрических спецификаций и т.д.)
- Используются ли характеристики или только номенклатура
- Нужен ли сложный поиск номенклатуры по набору свойств

**Comment by kodermax** [comment]
1. Заявка должна появится после согласования по нажатию кнопки "Отправить в 1с".
2. Гостевой не нужен.
3. Пока нет.
4. Нет.
5. Характеристики нужны.
6. Нет.

**Comment by unpete** [comment]
- Какая типовая 1С будет использоваться
- Какие отчеты и печатные формы должны быть доступны в "онлайн заказах"

**Comment by kodermax** [comment]
1. УПП.
2. Никакие.

**Comment by unpete** [comment]
Ок. Сегодня вечером накидаю прототип.
Чтобы получилось ближе к жизни, можете изготовить компактную dt-шку с номенклатурой и ценами, но без документов и конфиденциальной информации?

**Comment by kodermax** [comment]
Ок. сейчас сделаю.
А номенклатура в CouchDB будет меняться в реальном времени?

**Comment by unpete** [comment]
> А номенклатура в CouchDB будет меняться в реальном времени

Конечно. Можно синхронизировать любые документы и справочники.
Регистры так же, можно синхронизировать, но это требует дополнительных усилий.
Штатный сценарий: вместо регистров используем map/reduce индексы CouchDB

**Comment by kodermax** [comment]
Синхронизация происходит через веб-сервисы?

**Comment by unpete** [comment]
> Синхронизация происходит через веб-сервисы?

Нет. Посмотрите исходник [библиотеки интеграции](https://github.com/oknosoft/metadata.js/tree/master/integration_1c)
Можно не публиковать вообще никаких сервисов 1С и не зависеть от доступности 1С.

**Comment by kodermax** [comment]
Теперь понятно.
А замена CouchDB на MongoDB, возможна?

**Comment by unpete** [comment]
В CouchDB из коробки работает CRDT - распределенная репликация. В MongoDB такой прелести нет.
На больших проектах (от 100 млн. транзакций в день) можно задействовать [Couchbase](http://www.couchbase.com/) - для него есть совместимый  шлюз репликации.

**Comment by kodermax** [comment]
Ваш обмен будет работать только на 8.3.8?
![image](https://cloud.githubusercontent.com/assets/590985/17020730/e6248d62-4f4b-11e6-9adf-215b876be5fd.png)

**Comment by unpete** [comment]
Пересобрать библиотеку интеграции под старую платформу не проблема, но может быть проще обновить платформу на сервере?
УПП1.3, КА1.1 и УТ11 прекрасно работают под 8.3.8.

**Comment by kodermax** [comment]
А можете рядышком приложить файл для 8.2
А то сервер быстро не обновить..

**Comment by kodermax** [comment]
Есть данные о том выдержит ли браузер компьютера с 2 гигами памяти metadata.js ?

**Comment by unpete** [comment]
> выдержит ли браузер

metadata - это платформа. На ней можно сделать приложение, которое съест 10Gb, а можно уместить все данные в 300Kb - зависит от задачи.
К примеру, [Заказ дилера](http://www.oknosoft.ru/zd/) очень бодро работает на телефонах и планшетах с 1Gb RAM

**Comment by unpete** [comment]
> приложить файл для 8.2

Предлагаю демо-стенд сделать на актуальной версии и если математика вам понравится, обсудим целесообразность сборки под 8.2.

**Comment by kodermax** [comment]
Ok, сейчас сделаю на 8.3

**Comment by unpete** [comment]
Не ожидал от УПП такой поганки. В КА1.1 и УТ10.3 (которые из той же линейки, что и УПП), БСП вклеено вполне аккуратно. Есть регистр _Кэш программных интерфейсов_, нормально работает справочник _Идентификаторы объектов метаданных_, актуальный набор _СтроковыхФункцийКлиентСервер_.
Я придерживаюсь правила "не снимать с поддержки и не изменять ни одного объекта поставщика".
Сборку _Библиотеки интеграции_ для УПП1.3 в воскресенье сделал, но это потребовало намного больше времени, чем планировал.
Следующий такт: демка _Заказы онлайн_, подключенная к вашей dt-шке.
Сделаю методом _отрезания лишнего_ из _Заказа дилера_.

**Comment by kodermax** [comment]
Спасибо.

**Comment by unpete** [comment]
Создан репозиторий [Заказы онлайн](https://github.com/oknosoft/order-online)
Живое демо доступно по ссылке https://light.oknosoft.ru/orders/, для входа в программу:
- В диалоге авторизации выбрать гостевого пользователя _Алгоритм_, нажать кнопку _Войти_
- При первой синхронизации, страница будет несколько раз перезагружена

----

#### Исходники рекомендуется читать в такой последовательности:
1.	https://github.com/oknosoft/order-online/blob/master/README.md
2.	Содержимое файлов в https://github.com/oknosoft/order-online/tree/master/src/modifiers
3.	Содержимое файлов https://github.com/oknosoft/order-online/tree/master/src
4.	https://github.com/oknosoft/order-online/blob/master/gulpfile.js
5.	https://github.com/oknosoft/order-online/blob/master/index.html

**Comment by kodermax** [comment]
Спасибо,
Буду пробовать теперь это скрестить с моим reactjs приложением.

**Comment by eks1985** [comment]
Демо не работает.

**Comment by unpete** [comment]
> Демо не работает.

Какое именно? Можно ссылку и текст ошибки из консоли браузера?

**Comment by eks1985** [comment]
Вот это https://light.oknosoft.ru/orders/

Сейчас проверил - заработало, но скриншот с ошибками когда не работало я  сохранил.
Просто висело бесконечное окошко "синхронизация"

![errors](https://cloud.githubusercontent.com/assets/15969757/20488504/512a0740-b018-11e6-93c6-83fd128a9a20.png)

**Comment by unpete** [comment]
Наверное, в примере неаккуратный код обработки первого запуска.
С учетом того, что усилия сейчас направлены на v2, предлагаю на эту ошибку забить.

**Comment by bizsystems** [comment]
Помогите разобраться с этим демо-примером. Никак не могу найти в каком файле реализован отбор заказов по статусам. В buyers_order_form_list нашел реализацию списка выбора вариантов, а вот как сама фильтрация накладывается понять не могу.  Догадываюсь что фильтр происходит методом $p.doc.buyers_order.rep_planing(report, rid), где rid выбранный вариант, но где искать и модифицировать этот метод не понимаю.

**Comment by unpete** [comment]
> отбор заказов по статусам

В базе couchdb создан индекс. Код индекса, скорее всего, есть в 1С в макете обработки `ИнтеграцияАдминистрирование`. На всякий случай, дублирую здесь:
````javascript
function(doc){
var key;
if (doc._id.substr(0, 16)=='doc.buyers_order') {
  if(doc.obj_delivery_state=='Шаблон') key='template';
  else if(doc.obj_delivery_state=='Отправлен') key='sent';
  else if(doc.obj_delivery_state=='Отклонен') key='declined';
  else if(doc.obj_delivery_state=='Подтвержден') key='confirmed';
  else if(doc.obj_delivery_state=='Архив') key='zarchive';
  else key='draft';
  var d=doc.date.split('T')[0].split('-');
}else if(doc.date){
var d0=doc.date.split('T');
if(d0.length>1){
var d=d0[0].split('-');
key = doc._id.split('|')[0]
}}
if(key) emit([key,Number(d[0]),Number(d[1]),Number(d[2]),(doc.number_doc||doc.id||'')+(doc.note ? ' ' + doc.note : '')], null);
}
````
Далее, см. модуль [buyers_order_form_list.js](https://github.com/oknosoft/order-online/blob/master/src/modifiers/documents/buyers_order_form_list.js#L68) - там в зависимости от текущей строки дерева статусов в фильтр подмешивается значение отбора.
