### ISSUE TITLE
Интеграция с 1с

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#135]
![image](https://cloud.githubusercontent.com/assets/590985/17585166/dc7bf34a-5fc2-11e6-88f4-1ce01dad53cb.png)
А для чего эта обработка нужна?

**Comment by unpete** [comment]
Это аналог типовой обработки выгрузки-загрузки, но в ней доработан конструктор запросов для тонкого клиента

**Comment by kodermax** [comment]
Регламентное задание **Сессии легкого клиента** выдает ошибку 
![image](https://cloud.githubusercontent.com/assets/590985/17586441/7ccb21a2-5fca-11e6-90c3-8ccb02d400cf.png)

**Comment by unpete** [comment]
Наверное, это платформа старая, в которой #Область и #КонецОбласти не поддержаны.
Я использовал 8.3.8 в режиме совместимости с 8.2.
Надо будет выкинуть из всех текстов операторы группировок.
В своей базе поправьте руками

**Comment by kodermax** [comment]
ага хорошо.

**Comment by kodermax** [comment]
Еще одна ошибка
![image](https://cloud.githubusercontent.com/assets/590985/17587399/c39057e6-5fd0-11e6-8ebb-5d5da0f7788c.png)

**Comment by unpete** [comment]
Поставлю платформу 8.2. и пересоберу на ней.
Похоже, в режим совместимости, учтены не все особенности старой платформы.

**Comment by kodermax** [comment]
Большое спасибо.

**Comment by kodermax** [comment]
почему так сложно сделали, такой формат
![image](https://cloud.githubusercontent.com/assets/590985/17589291/8f427daa-5fdc-11e6-8d90-28243f626453.png)

**Comment by kodermax** [comment]
А где вы его генерировали?

**Comment by unpete** [comment]
> почему так сложно сделали, такой формат

Это стандартный кусочек из БСП.
Физически, данные завёрнуты в ХранилищеЗначения, но форма регистра "КешИнтерфкейсов", отображает их сериализацию в XML.

**Comment by unpete** [comment]
> возможность настроить работу со старой версией 1Cv7

Возможность есть, но моё время до конца 2017 года уже продано.
Посмотрите код [библиотеки интеграции](/oknosoft/metadata.js/tree/master/integration_1c). Секретиков там нет, но объём библиотеки внушительный. Для перевода на v77 потребуется приложить усилия.
