### ISSUE TITLE
Регистрация объектов в CouchDb

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#138]
При нажатии Регистрировать пишет так обмена, и не пишет результат, успешно этот или нет
![image](https://cloud.githubusercontent.com/assets/590985/17614901/cbcd1604-6072-11e6-87ed-7c320311a6df.png)

**Comment by unpete** [comment]
Учтено в актуальной версии [библиотеки интеграции](https://github.com/oknosoft/metadata.js/tree/master/integration_1c)
