### ISSUE TITLE
Проверка соединения с КучейДб и кнопка записать

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#139]
Нет кнопки записать и проверка соединения
![image](https://cloud.githubusercontent.com/assets/590985/17615001/92cfda7a-6073-11e6-80d0-19a9f6e145ce.png)

**Comment by unpete** [comment]
Кнопка "Записать" есть. Кнопки "проверить", действительно нет. И она, действительно, была бы полезна.

**Comment by kodermax** [comment]
Но кнопка записать находится на другой вкладке, и да нее сложно догадаться)

**Comment by kodermax** [comment]
увидел кнопку записать не сразу, совсем не заметная.

**Comment by unpete** [comment]
> совсем не заметная

Это из-за 8.2., в которой я обработку пока не открывал.

**Comment by unpete** [comment]
Кнопка проверки соединения добавлена в [библиотеке интеграции v2.3.1.220](https://github.com/oknosoft/metadata.js/tree/master/integration_1c)
