### ISSUE TITLE
Ошибка формирования пути к CouchDb

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#141]
У меня почему то формируется переменная не правильно, отсутствует сам сервер в нём
![image](https://cloud.githubusercontent.com/assets/590985/17616594/7d5cda2a-607e-11e6-949e-c35d39716a7a.png)

**Comment by unpete** [comment]
Путь правильный.
Имя сервера, протокол и порт живут в HTTPСоединении, а не в HTTPЗапросе
