### ISSUE TITLE
Ошибка с пользователями

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#146]
Нашёл ошибку, здесь нет проверки на группу, он берет группу и выдает ошибку.
![image](https://cloud.githubusercontent.com/assets/590985/17727761/1e5fa8ec-6464-11e6-9da1-cb4e0eacca7e.png)

**Comment by unpete** [comment]
В БСП справочник пользователи - плоский, без иерархии.

17.08.2016 12:20 пользователь "Maksim" <notifications@github.com> написал:

**Comment by kodermax** [comment]
А у нас есть иерархия в УПП.

**Comment by unpete** [comment]
Ок, уже учтено в библиотеке интеграции - выложу при ближайшем обновлении.
