### ISSUE TITLE
Ошибка при выгрузке больших данных

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#147]
Выскачило при выгрузке
![image](https://cloud.githubusercontent.com/assets/590985/17729066/fd8a1010-646a-11e6-8da7-3f054136f733.png)
успело выгрузить 
![image](https://cloud.githubusercontent.com/assets/590985/17729075/0822e2b8-646b-11e6-9ef5-0fb1c8ee7e28.png)

**Comment by unpete** [comment]
1. Большие выборки должны записываться кусочками по 100 или 1000 об'ектов.
Возможно, в последних сборках в этом месте ошибка, но раньше под 8.3
работало нормально
2. Писать рекомендуется в локальную Couchdb, стоящую рядом с сервером 1С,
на которой настроена репликация с облачной базой.
3. Любые транзакции, длинее 3 секунд, я считаю критическими архитектурными
ошибками. Надо анализировать и корректировать постановку задачи.

17.08.2016 13:09 пользователь "Maksim" <notifications@github.com> написал:

**Comment by kodermax** [comment]
Повторно выгрузил, вроде нормально прошло, видимо отладчик виноват был.
