### ISSUE TITLE
Есть возможность отказаться от PouchDB

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#148]
Чтобы юзер в онлайне обращался только к couchdb?
Чтобы не было синхронизации с pouchdb?

**Comment by unpete** [comment]
Отказаться можно не только от pouchdb. Можно сделать клиентскую и серверную части на json-файлах или sql (собственно, та и было сделано в ранних версиях). Или дёргать каждый раз сервер 1С.
Скорее всего, проблема не в pouchdb, а в том, как вы пытаетесь её использовать в своём проекте.
У наших объектов данных из коробки 5 режимов кеширования: ram, doc, doc_remote, meta и e1cib. Плюс, есть режимы "не из коробки". Например, в "Заказе дилера", создаются миллионы характеристик номенклатуры. Это не гипербола - реальные миллионы. Никаких задержек и паразитного трафика эти характеристики не порождают. Используется фильтрованная репликация.

**Comment by unpete** [comment]
### Слои (как у Шрека и лука):
- В CouchDB не обязательно гнать все записи из 1С
- В PouchDB не обязательно гнать все записи из CouchDB
- В память браузера не обязательно загружать все записи из PouchDB

**Comment by kodermax** [comment]
:) Сейчас я пытаюсь запустить, что есть, и потом начну разбираться как устроено и выпиливать не нужное.
