### ISSUE TITLE
Ошибка. Не добавляется заявка

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#149]
При нажатии на плюсик, ошибка
![image](https://cloud.githubusercontent.com/assets/590985/17731791/9ac39516-6477-11e6-86f3-295b3df54c47.png)

**Comment by unpete** [comment]
На картинке не видно самого главного: какое именно проперти "кен нот би рид" и у какого объекта,
Скорее всего, версия metadata.js не соответствует ожиданиям app.js
