### ISSUE TITLE
Нет картинок

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#150]
Где взять эти картинки
![image](https://cloud.githubusercontent.com/assets/590985/17738329/789a64c0-6499-11e6-951d-498363636418.png)

**Comment by unpete** [comment]
https://github.com/oknosoft/order-online/tree/master/dist/imgs
Дополнительно, в https://github.com/oknosoft/order-online/tree/master/src/templates/imgs есть исходник splash.psd - в нём можно отредактировать заставку при запуске
