### ISSUE TITLE
Не получается установка metadata-js по инструкции (но в linux)

### ISSUE THREAD

**Issue by FSerg** [oknosoft/metadata.js#172]
Добрый день.
Устанавливаю metadata-js по инструкции http://infostart.ru/public/540168/
Но делаю все это в вирт.машинке с linux Ubuntu 16.04,
node'а установилась v6.8.1

команды 
`npm install -g metadata-js`
`npm install -g gulp-cli`
выполняется без ошибок

а вот 
`metadata init`
получаю ошибку:
`/usr/bin/env: ‘node\r’: No such file or directory`

и судя по всему ‘node\r’ - это где-то в коде перенос строки стоит в кодировке Windows или типа того

Где и что можно посмотреть?
Или вариант только ставить все под Windows?

**Comment by unpete** [comment]
`metadata init` разворачивает в текущей папке начальный образ приложения htlloworld
Вместо `metadata init` можно выполнить `git clone https://github.com/oknosoft/helloworld.git` - результат будет тем же

> Или вариант только ставить все под Windows?

Отлаживать лучше в той среде, к которой привыкли. Нет смысла устанавливать windows, если обычно работаете в linux или mac

**Comment by FSerg** [comment]
Ок, через git clone получилось пройти дальше :)
Как только развернул couchDB почему-то сразу создал админскую учетку.
И кажется теперь из-за этого не собирается демо-приложение.
Т.е. при выполнении:
`gulp full`
выдает:
```
{ error: 'unauthorized',
  reason: 'Name or password is incorrect.',
  name: 'unauthorized',
  status: 401,
  message: 'Name or password is incorrect.' }
(node:31515) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError in plugin 'metadata-prebuild'
Message:
    Cannot read property 'enm' of undefined
(node:31515) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): [object Object]
```
А в package.json я не нахожу как прописать данные авторизации в couchDB, там ведь только путь к серверу couch'а
Или я неправильно ошибку интерпретирую?

**Comment by unpete** [comment]
В последних версиях metadata.js к базе _meta_ разрешен анонимный доступ.
Ранее, для этой базы использовался предопределенный пользователь "guest" с паролем "meta" - создавался при инициализации couchdb со стороны 1С.
В экзотических случаях, в базе _meta_ могут кешироваться некоторые документы и справочники.
В штатном режиме, там только метаданные и эта база используется ТОЛЬКО при пересборке проекта и не тянется в веб-приложение.
