### ISSUE TITLE
Стенд для разработки-отладки v2

### ISSUE THREAD

**Issue by unpete** [oknosoft/metadata.js#177]
- [x] Создать branch v2 в [helloworld](/oknosoft/helloworld/tree/v2)
- [x] Подключить ядро и ui v2
- [x] Реализовать функциональность демо helloworld

**Comment by unpete** [comment]
про подключение библиотек см https://github.com/oknosoft/metadata.js/pull/180

**Comment by unpete** [comment]
# Задача текущего этапа
## Повторить в _metadata-react-ui_ функциональность, реализованную в _v0.12_
- [ ] Уточнить состав и постановку задачи по [компонентам ui](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui)
- [ ] Отранжировать по срочности-важности
- [ ] Реализовать

Задачи, лежащие на поверхности перечислю прямо здесь:
### Поле ввода
- [ ] Дополнить описание [DataField](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/DataField)
- [ ] Поддержка всех типов данных - сейчас компонент работает с ссылочными и текстовыми типами данных. Есть редактор дат из material-ui (довольно мерзкий), нет редактора чисел
- [ ] Для ссылочных данных, кроме выбора из выпадающего списка, нужен вызов формы выбора [DataList](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/DataList) и полная поддержка _параметров выбора_ и связей _параметров выбора_ - сейчас это, вроде работает для выпадающего списка - нужно приклеить и отладить для формы
- [ ] Стили и поведение поля ввода нужно приблизить к тому, что предлагает в своём тонком клиенте 1С. Уже столкнулся с замечаниями пользователей, которые ожидают от поля ввода привычного для них поведения
- [ ] Реализовать тесты для режимов размещения как на форме, так и в табличной части - компонент должен вести себя одинаково (для табчасти используется обёртка [DataCell](/oknosoft/metadata.js/blob/develop/packages/metadata-react-ui/src/DataField/DataCell.js))

### Модальный диалог
- [ ] Дополнить описание [Dialog](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/Dialog)
- [ ] Сейчас используется [Dialog из material-ui](http://www.material-ui.com/#/components/dialog) - его нельзя таскать за заголовок, нельзя свернуть, вложенные диалоги вписаны в родительский диалог - поганок много. Имеет смысл сделать свою обертку диалога (модальной или немодальной формы). Учесть свойства управляемой формы 1С и [react-panels](http://theadd.github.io/react-panels/bower_components/react-panels/examples/floating/index.html)

### Панель
- [ ] Дополнить описание [FlexPanel](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/FlexPanel)
- [ ] Нужен компонент со свойствами, близкими к _Группе формы_ из управляемого интерфейса 1С - на панелях должны уметь размещаться другие панели и компоненты, панели должны уметь сжиматься, сворачиваться и растягиваться, поддерживать сплиттер, заголовки и прочие бантики. Рассмотреть [react-grid-layout](https://github.com/STRML/react-grid-layout) и [react-flex-layout](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/FlexPanel/react-flex-layout)

### Табы (закладки)
- [ ] Дополнить описание [Tabs](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/Tabs)
- [ ] По сути, закладка - это разновидность панели. Возможно, правильнее панель сделать HOC, который умеет показывать себя как обычную панель либо как закладку. Рассмотреть [react-panels](http://theadd.github.io/react-panels/bower_components/react-panels/examples/floating/index.html)

### Динамический список
- [ ] Дополнить описание [DataList](/oknosoft/metadata.js/tree/develop/packages/metadata-react-ui/src/DataList)
- [ ] Поддержать отборы, сортировки, группировки
- [ ] Поработать над стилями, поведением и быстрыми кнопками (как в 1С)

**Comment by nikches** [comment]
Работаю над модальным диалогом. За основу взят пакет [react-panels](https://github.com/Theadd/react-panels/). Сейчас это выглядит так: 
![dialog](https://cloud.githubusercontent.com/assets/12497894/23342101/4ba980ae-fc65-11e6-9e70-a493e4827ef4.png)
Необходимо доработать стиль и оптимизировать производительность при перемещении. Пакет из репозитория npm является устаревшим, поэтому была взята версия с github.

На данном этапе интерфейс компонента такой:
```javascript
title: string,
tabs: object, // Object with title:tab pairs.
actions: array,
isVisible: bool,
width: number,
```

**Comment by unpete** [comment]
Настройки динсписков и табличных частей предполагают наличие в couchdb специальных индексов и служебных элементов справочника _scheme_settings_.
По названию варианта настроек _Основная_, можно предположить, что используется устаревшая dt-шка демо-примера. Если это так, более свежий вариант [лежит здесь](https://github.com/oknosoft/metadata.js/tree/master/integration_1c)
Couchdb должна быть 2.0. В windowbuilder я уже использую mango индексы. Планирую их задействовать и в типовой части metadata.v2.

Вопросы по компоненту:
- высота формируется автоматически по содержимому или забыл перечислить в списке свойств?
- actions будут располагаться так же в шапке справа от табов?
- стандартные для десктопа кнопки свернуть-развернуть-закрыть были бы полезны
- resizible?
- иерархия модальности - открытые из диалога модальные диалоги должны уметь блокировать родителя
- viewport - дети должны уметь как жить внутри родительского диалога, так и быть независимыми на весь экран
- наверное, будет правильным предусмотреть возможность приклеивать _actions_ и _tabs_ не только к диалогу, но и любому другому компоненту

**Comment by nikches** [comment]
Высота компонента будет в списке свойств. Сейчас в `react-panels`, если не ошибаюсь, нет функции изменения размеров окна. Необходимо будет форкнуть репозиторий `react-panels`. Остальными вопросами тоже займусь.

**Comment by nikches** [comment]
Я так понимаю текущая задача по реализации поля ввода сводится к повторения функционала из metadata.js v0.12. Сверх этого на данный момент времени ничего не планируется? Основная цель - это добиться максимальной схожести с полями 1C? И в дополнении к этому расширить документацию и добавить тесты.

**Comment by unpete** [comment]
> сводится к повторения функционала из metadata.js v0.12

Скорее, к повторению функционала из _1С Такси_. В v0.12 нет прямого аналога полю ввода. Для редактирования строк, дат, чисел и ссылочных типов там используются разные элементы управления. В v2.0 это разруливается одним высокоуровневым компонентом, который подключает разные вложенные компоненты в зависимости от метаданных поля и типа текущего значения.

По модальному диалогу пока вижу только прототип. Вероятно, ваши последние изменения еще не оформлены в PR?

**Comment by nikches** [comment]
По полю ввода на данный момент всё ясно. В ближайшее время сделаю pull request с изменениями Dialog.

**Comment by nikches** [comment]
Так как `Table` из `react-virtualized` не имеет горизонтальной прокрутки, но неплохо было бы иметь фиксированную первую строку и первый столбец (заголовки сетки) предлагаю использовать [MultiGrid](https://bvaughn.github.io/react-virtualized/#/components/MultiGrid).

**Comment by unpete** [comment]
Ок, мультигрид - то, что надо. Возможность фиксировать шапку и первые
колонки будет полезной.

**Comment by nikches** [comment]
В качестве компонента выбора дат можно взять [react-datepicker](https://hacker0x01.github.io/react-datepicker).

**Comment by unpete** [comment]
До конца недели я в командировке, отвечу по возвращении.

**Comment by unpete** [comment]
> В качестве компонента выбора дат взять react-datepicker

Можно и его. Важно не забыть:
- форматы, заданные в метаданных и (или) компоненте
- ввод даты и времени с клавиатуры, мышкой и пальцем
- ввод интервалов
