### ISSUE TITLE
Объединить и переместить *.scss

### ISSUE THREAD

**Issue by unpete** [oknosoft/metadata.js#178]
Стили, описанные индивидуально для каждого компонента [metadata-react-ui](https://github.com/oknosoft/metadata.js/tree/master/packages/metadata-react-ui) имеет смысл объединить в общий css файл и вместо `className={classes.name}` использовать  `className={'class-name'}`

**Comment by nikches** [comment]
Какие преимущества может дать объединение?

**Comment by unpete** [comment]
> Какие преимущества может дать объединение?

Есть стили приложения. Их пользователи создают и редактируют самостоятельно. 
Есть стили библиотеки. Общий файл стилей избавит от дублирования классов css, задействованных в разных компонентах

**Comment by nikches** [comment]
Я представляю себе такое использование:
```javascript
// ComponentName.js
import '../path/to/common.scss'; // общие стили для библиотеки
import './ComponentName.scss'; // стили для конкретного компонента
```
