### ISSUE TITLE
Параллельный доступ к базе данных

### ISSUE THREAD

**Issue by nikches** [oknosoft/metadata.js#189]
Как решается вопрос с одновременной (почти одновременной) записью разными пользователями в базу данных? Например уникальность номера у документа 1С.

**Comment by FSerg** [comment]
Не знаю, как именно сделано у метадаты.
Думаю, при онлайн режиме запрашивается с 1С.
А при офлайн режиме можно разруливать префиксами пользователей.

**Comment by unpete** [comment]
> уникальность номера у документа 1С

Каждый пользователь имеет уникальный префикс нумерации документов и кодов справочников

> Думаю, при онлайн режиме запрашивается с 1С

В штатном режиме, клиент metadata никогда не обращается к серверу 1С
