### ISSUE TITLE
Порядок развития проекта

### ISSUE THREAD

**Issue by allustin** [oknosoft/metadata.js#2]
Несколько вопросов:

1. лицензия используется достаточно странная - при нескольких фазах её прочтения выходит, что вы запрещаете делать форк этого проекта. Что означает что вы используете github только как хостинг исходного кода для чтения. Просьба чуть расширить описание вариантов легального использования согласно лицензии.

2. не наблюдаю в вашем проекте тестов, однако вижу что в описание пакета включено игнорирование каталога тестов. отсюда вопрос - используется ли тестирование в проекте ?

**Comment by unpete** [comment]
Добрый день, Алексей.
1. Странность лицензии подтверждаю. Текст будет доработан. Проект ещё очень
молод, как в части кода, так и в части эксплуатационной и юридической
документации. Хочется оставить полностью открытый код, но с коммерческим
использованием. Лицензия - на разработчика.
2. Понимаю, что без автоматических тестов, доверия к проекту не будет. Их
реализация в планах есть, но из-за дефицита ресурсов - не в самых ближайших.
09.07.2015 1:42 пользователь "Alexey Lustin" <notifications@github.com>
написал:

**Comment by allustin** [comment]
Спасибо. Мне было важно понять развитие на перспективу. По мере развития будем пробовать подключиться ;-)
