### ISSUE TITLE
Метаданные конкретного приложения

### ISSUE THREAD

**Issue by eks1985** [oknosoft/metadata.js#200]
Пример: подключили библиотеку интеграции к базе 1с, выполнили настройку couchdb и выгрузили туда метаданные и данные. 

Теперь конструируем конректное веб приложение. Для этого нам нужны метаданные отправленные в couchdb. 

Правильно я понимаю, что метаданные подтягиваются в наше приложение npm скриптом ' `prebuild:meta`?

Результатом его работы является файл `src/metadata/init.js` ?

**Comment by unpete** [comment]
Да, совершенно верно.
Если исходные метаданные большие (ERP2.0), то базовый состав объектом метаданных мы определили в обработке _Интеграция панель администрирования_ в 1С.
Если метаданные нужно дополнительно обрезать для суперлегкого рабочего места (кассир или кладовщик), внутри `prebuild:meta` можно сделать дополнительный фильтр (пример есть в типовом файле)
Есть возможность строить несколько веб-интерфейсов с разным набором метаданных к одним и тем же метаданным couchdb
Конфигуратор 1С используется исключительно, как редактор метаданных. В принципе, эти метаданные можно править обычным текстовым редактором.
Так же, в metadata.v2 запланированы компоненты ui для редактирования метаданных
