### ISSUE TITLE
TypeScript поддержка

### ISSUE THREAD

**Issue by allustin** [oknosoft/metadata.js#249]
прикрутить как минимум библиотеку "тайпингов"

//cc @nixel2007

**Comment by unpete** [comment]
imho, в ядре метадаты оно лишнее. Данные у нас и так ссылочно типизированы, реализовано автоприведение типов
````javascript
// создаём документ-объект продажа
const doc = $p.doc.sale.create();
// присваиваем номенклатуру, найденную по наименованию
doc.nom = $p.cat.nom.by_name('огурец');
// тот же результат, что и в прошлой строке - присваиваем номенклатуру, найденную по guid
doc.nom = $p.cat.nom.by_ref('a7c5be2f-d52c-454f-a3c5-031b561244ab');
// тот же результат, что и в прошлой строке - в поле nom окажется ссылка на номенклатуру, но никак не строка guid
doc.nom = 'a7c5be2f-d52c-454f-a3c5-031b561244ab';
console.log(doc.nom.name); // огурец
````

Любителям .net никто не мешает и сейчас использовать TypeScript в прикладных решениях, дёргая интерфейсы метадаты.
Наверное, ts мог бы быть полезен для автодокументирования свойств и методов объектов данных, но файл с [описанием метаданных](https://github.com/oknosoft/helloworld/blob/v2/src/metadata/init.js), вроде, ничем не хуже - система генерирует его при сборке проекта.

**Comment by nixel2007** [comment]
@unpete описание-то может и есть. Я смотрю hello-world, там в, например, main.js или в различных view есть переменная $p (как и в вашем примере выше). Т.к. нигде нет объявления этой $p (ни в импорте, ни в конструкторе), то возникает вопрос - как вообще обстоит дело с автокомплитом? Я нажимаю точку и... не получаю ничего.

JSDoc в стиле `@param prm {Object}` тоже радости не доставляют.

P.S. Не совсем понял наброс на .net. Да и ts - это не только буковки после двоеточий, это еще и проверка типов compile-time

**Comment by unpete** [comment]
> смотрю hello-world

Версию 0.12 я похоронил в позапрошлом году. Есть [hello-world v2.0](https://github.com/oknosoft/helloworld/tree/v2). Автокомплит и прочие бантики своими руками делать не буду. Если найдутся энтузиасты - прикрутят. Мне хватает реальных задач. Например, движок компоновки для настройки динсписков, отчетов и табличных частей.
