### ISSUE TITLE
Кнопка получения произвольного объекта в панели администрирования библиотеки интеграции

### ISSUE THREAD

**Issue by nmivan** [oknosoft/metadata.js#256]
Функция ИнтеграцияСериализацияСервер.CouchDB_ПолучитьОбъект есть, но не использована.

Добавить кнопку в панель администрирования, чтобы могла загрузить объект по ключу.

**Comment by unpete** [comment]
Лучше, наверное, не записывая, заполнить объект и открыть его форму с
признаком модифицированности.

**Comment by nmivan** [comment]
Да, там есть такая функциональность.

**Comment by nmivan** [comment]
Кнопка грузит объект, может его сразу записать в ИБ, может создать новый объект, заполнить и открыть для ручной записи. Вики напишу.
