### ISSUE TITLE
Отсутствует mime_lookup

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/metadata.js#257]
При попытке получить docx документ 
Файл 
```js
metadata.js/src/common.ui.js 

$p.utils.__define({
  docxtemplater: { }
765:    var out = this.getZip().generate({type: "blob", mimeType: $p.utils.mime_lookup('docx')});
```
Uncaught (in promise) TypeError: utils.mime_lookup is not a function

В коде вижу, что mime.js есть и его код импортирован в utils .  
Но в живой системе mime_lookup отсутствует. 
А к вызову docx привязаны типовые договоры с физ. и юр. лицами.

**Comment by unpete** [comment]
Спасибо, https://github.com/oknosoft/metadata.js/commit/48032ec3e98dfcf6e361d93df3170f893f1c1347
