### ISSUE TITLE
wiki по загрузке данных в библиотеке интеграции

### ISSUE THREAD

**Issue by nmivan** [oknosoft/metadata.js#258]

**Comment by nmivan** [comment]
Добавлены и/или изменены:
[home](https://github.com/oknosoft/metadata.js/wiki)
[Библиотека-интеграции-с-1С-выгрузка-данных-в-CouchDB](https://github.com/oknosoft/metadata.js/wiki/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81-1%D0%A1-%D0%B2%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B2-CouchDB)
[Библиотека-интеграции-с-1С-загрузка-данных-из-CouchDB](https://github.com/oknosoft/metadata.js/wiki/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81-1%D0%A1-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8%D0%B7-CouchDB)
[Библиотека-интеграции-с-1С-панель-администрирования](https://github.com/oknosoft/metadata.js/wiki/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81-1%D0%A1-%D0%BF%D0%B0%D0%BD%D0%B5%D0%BB%D1%8C-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
[Библиотека-интеграции-с-решениями-на-платформе-1С](https://github.com/oknosoft/metadata.js/wiki/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81-%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8-%D0%BD%D0%B0-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B5-1%D0%A1)

**Comment by unpete** [comment]
Дополнил описание на странице про панель администрирования

**Comment by nmivan** [comment]
спасибо.
