### ISSUE TITLE
Обработка массовой загрузки

### ISSUE THREAD

**Issue by unpete** [oknosoft/metadata.js#275]
- Не понятно, как воспользоваться произвольным запросом
- Тип поля база лучше сделать перечислением с отбором через параметры выбора
- Тип объекта метаданных можно автокомплитить или дать выпадающий список
- Верхнюю панель с единственной кнопкой _еще_ можно спрятать, кнопку _прочитать_ можно перенести в командную панель табчасти - освободится место

**Comment by nmivan** [comment]
ты как вообще в эту обработку попал?

**Comment by unpete** [comment]
Она включена в core библиотеки интеграции
