### ISSUE TITLE
Поиск по табличным частям

### ISSUE THREAD

**Issue by nmivan** [oknosoft/metadata.js#281]
Какой способ оптимален для поиска по табличным частям?
Есть в wb справочник delivery_directions, в нем табличная часть, в ней колонка. Мне надо найти элементы справочника по значению в этой колонке.
В alasql не разобрался, как осуществить поиск по всем таб.частям элементов этого справочника.

@unpete, подскажешь?

**Comment by unpete** [comment]
Если элементы этого справочника живут в ram, можно пробежаться по элементам
````javascript
let ok;
$.cat.delivery_directions.forEach(({composition}) => {
  if(composition.some((v) => v===find)){
    ok = true;
    return false;
  }
});
````

Если направлений доставки тысячи и они живут в doc, нужно написать map-индекс couchdb, в котором развернуть табчасть

**Comment by nmivan** [comment]
Пробежаться это понятный вариант, его на крайний случай оставлял.
Справочник живет в doc_ram.

А можно сделать кеш? Это будет объект, в котором будет лежать соответствие элементов и направлений доставки. Элементы - это подразделения и районы. Ну т.е. это будет вывернутый наоборот справочник.

**Comment by unpete** [comment]
Хороший вариант: кешировать в doc в браузере и в doc_ram на сервере. Нам ведь ОЗУ не надо экономить. В кеше особого смысла не вижу. Обращение по сети к couchdb за остатками всё равно сожрет больше времени.

**Comment by unpete** [comment]
Кеш можно сделать с целью поупражняться в js

**Comment by nmivan** [comment]
Это задача из планирования, она на сервере вроде.
Сделаю кеш.

**Comment by nmivan** [comment]
Глянь [PR](https://github.com/oknosoft/windowbuilder-planning/pull/21), пожалуйста.
Есть критичные ошибки?
