### ISSUE TITLE
Подробное описание ошибок при первом запуске CouchDB 

### ISSUE THREAD

**Issue by Ilyanski** [oknosoft/metadata.js#286]
При нажатии "Создать базы и пользователей" возникает Ошибка: {"error":"not_found","reason":"Database does not exist."} 
Сделать: "Нет базы (Название Базы) в CouchDB, для записи баз и пользователей".

**Comment by unpete** [comment]
Проблема возникает, если установка couchdb не доведена до конца (не созданы системные базы данных)
