### ISSUE TITLE
fatal: repository 'https://github.com/unpete/react-panels.git' not found

### ISSUE THREAD

**Issue by olegius88** [oknosoft/metadata.js#308]
здравствуйте. не получается установить metadata по командам 
npm install --save metadata-js  # node
npm install -g metadata-js      # command line
ни из консоли, ни из node. 

При открытии репозитория, выходит ошибка:
![image](https://user-images.githubusercontent.com/7477933/35779101-ff2076b6-09f1-11e8-8591-a87c4f4f9af6.png)

**Comment by olegius88** [comment]
Вот полный текст ошибки:
F:\IdeaProjects\metadata-1c>npm install --save metadata-js
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/unpete/react-panels.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/unpete/react-panels.git/' not found
npm ERR!
npm ERR! exited with error code: 128

**Comment by unpete** [comment]
Что вы пытаетесь сделать? Зачем потребовалось устанавливать `metadata-js` из npm?

**Comment by olegius88** [comment]
Я пытаюсь начать работу с metadata. Видимо, не с того начал, судя по вашему вопросу. 

Я уже нашел https://github.com/oknosoft/metadata-devtraining/wiki/Задача-№-1.-Разворачиваем-среду-разработки

**Comment by unpete** [comment]
`metadata-js` - это ветка v0.12 - на неё можно время не тратить.
Актуальные библиотеки [см. здесь](https://github.com/oknosoft/metadata.js/tree/develop/packages)
