### ISSUE TITLE
Продолжение загрузки при ошибке на одном из объектов

### ISSUE THREAD

**Issue by nmivan** [oknosoft/metadata.js#310]
Сейчас, если происходит ошибка на одном из объектов - например, он не смог записаться в 1С по внутренним причинам 1С - то загрузка остальных объектов останавливается.
При следующем входе он пытается загрузить ту же пачку, и ситуация повторяется.
А снаружи этого не видно.

**Comment by unpete** [comment]
Imho это не ошибка, а способ гарантировать, что прочитаны все изменения

**Comment by nmivan** [comment]
Не актуально. Проверки при загрузке должны делаться по месту и в переопределяемых модулях.
