### ISSUE TITLE
Починить интерфейс

### ISSUE THREAD

**Issue by nmivan** [oknosoft/metadata.js#316]
Сейчас в Helloworld выглядит так:

![image](https://user-images.githubusercontent.com/29771561/37133392-fa3f2b98-22b4-11e8-8f89-03e5465ff505.png)

Все формы справа рисуются затененными и по ним мышкой не кликнуть.

**Comment by unpete** [comment]
Так оно выглядит на время выбора пункта меню на узких экранах.
Выбор пункта или клик по рабочей области или esc - прячет меню.
Если в форме, связанной с пунктом есть ошибка или ошибка в файле `menu_items`, может вставать колом, но это другой вопрос.

В 2.0.16-beta.53 в hw и во флаконе сделал ряд улучшений, в layout и drawer, которые давно ждали своей очереди. К текущему замечанию это не относится, но выравнивание и адекватность должны улучшиться.
