### ISSUE TITLE
FieldToggle (компонент для рисования флажков)

### ISSUE THREAD

**Issue by nmivan** [oknosoft/metadata.js#317]
Сырой и кривой, но вроде работает.
Буду дорабатывать, исходя из практики использования.

**Comment by unpete** [comment]
Желательно, чтобы это был внутренний компонент.
Автоформа или человек размещает DataField, cсвязанный с данными, а селектор внутри DataField в зависимости от типа поля и допсвойств, использует для отображения нужного реквизита FieldToggle.
Например, мы можем захотеть использовать этот элемент управления для редактирования числовых или строковых данных или наоборот, не использовать его для редактирования булевых.
