### ISSUE TITLE
ошибка npm install metadata-js

### ISSUE THREAD

**Issue by okumsky** [oknosoft/metadata.js#321]
Зависимый пакет отсутствует  

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/unpete/react-panels.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/unpete/react-panels.git/' not found
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by unpete** [comment]
`metadata-js` - это снятая с поддержки в 2016 году версия v0.12.
Актуальная версия v2 живёт [здесь](https://github.com/oknosoft/metadata.js/tree/develop/packages).
Так же, см.: https://github.com/oknosoft/metadata-devtraining и https://github.com/oknosoft/helloworld
