### ISSUE TITLE
Дублирование meta_cch_mgr 

### ISSUE THREAD

**Issue by okumsky** [oknosoft/metadata.js#328]
https://github.com/oknosoft/metadata.js/blob/687fa94e4e01c4fc1d093891f3481031c84e5815/packages/metadata-core/index.js#L192
https://github.com/oknosoft/metadata.js/blob/687fa94e4e01c4fc1d093891f3481031c84e5815/packages/metadata-core/index.js#L193

**Comment by unpete** [comment]
Спасибо, учту в ближайшем релизе
