### ISSUE TITLE
в схеме "Концепция и философия" на картинке вместо couchdb - pouchdb

### ISSUE THREAD

**Issue by qasef** [oknosoft/metadata.js#357]
в схеме "Концепция и философия" на картинке вместо couchdb - pouchdb

**Comment by qasef** [comment]
ошибся

**Comment by unpete** [comment]
Текст и картинки драматически устарели. Сейчас и концепция и философия совсем другие. Например, никакой 1С в серверной части давно нет.

**Comment by nosovk** [comment]
а можно их обновить? Мы по прежднему хотим использовать metadatajs как клиент к 1с для создания в ней документов. То есть сервер с 1с все же нужен как бы.

**Comment by unpete** [comment]
> То есть сервер с 1с все же нужен как бы

Если задача серьёзная (от 1000 пользователей, сотен филиалов, требованием к отказоустойчивости и нормальным бюджетом) - можем обсудить по почте info@oknosoft.ru
Если уверены, что вам нужно не web-приложение с прозрачной интеграцией с 1С, а именно клиент к web-сервису 1С, метадата вам не подходит.

**Comment by unpete** [comment]
> То есть сервер с 1с все же нужен как бы

Сервер 1С в нашем сценарии стоит в сторонке и периодически робко спрашивает у Couchdb, нет ли для него работы. Если накопились необработанные изменения, он их забирает и обрабатывает. Например, создаёт или меняет документы в своей базе.
