### ISSUE TITLE
Типы данных в 1С для интеграционных объектов

### ISSUE THREAD

**Issue by fao87** [oknosoft/metadata.js#359]
Добрый день! 
Подскажите пож-та, где можно найти информацию по описанию типов в 1С (какие объекты в какой тип нужно добавлять уже в рабочей сборке, не в демо-примере Hello World): 

Настроить состав определяемых типов ИнтеграцияНаборЗаписей, ИнтеграцияОбъект и ИнтеграцияСсылка
Объекты, включенные в состав определяемых типов ИнтеграцияОбъект и ИнтеграцияНаборЗаписей копируются в CouchDB автоматически подписками на события ИнтеграцияПриЗаписиНабораЗаписей и ИнтеграцияПриЗаписиСправочника

Заранее спасибо!

**Comment by unpete** [comment]
> какие объекты в какой тип нужно добавлять уже в рабочей сборке

Это зависит от вашей задачи. Лишних метаданных и данных гнать в сервис точно не надо.
Включаете по минимуму те классы, без которых web-приложению не обойтись.
Принимаете решение, где и какие объекты будут кешироваться и реплицироваться, задаёте синонимы, фильтруете лишние поля и табчасти, пишете обработчики трансформации при записи в облако и при чтении из облака.
Правила платной техподдержки описаны [здесь](http://www.oknosoft.ru/poslednie-novosti/timing.html).
