### ISSUE TITLE
Пропал dev training

### ISSUE THREAD

**Issue by nosovk** [oknosoft/metadata.js#435]
https://github.com/oknosoft/metadata-devtraining/blob/master/README.md
Была раньше пошаговая инструкция, хороший how to.
И он пропал. Есть что-то взамен?

**Comment by unpete** [comment]
Только исходники самой метадаты. dev training сопровождать некому

**Comment by nosovk** [comment]
А старый был уже не актуален?
Сейчас можно только по примеру поднять свой проект? Или какая-то документация, howto все же есть?
