### ISSUE TITLE
Судьба сообщества изучения Metadata.js

### ISSUE THREAD

**Issue by a-grinyuk** [oknosoft/metadata.js#439]
Подскажите, прикрыли данное сообщество? Пошаговый инструкции не сохранили?

**Comment by unpete** [comment]
Никому не помогла пошаговая инструкция. Только вредила, создавая иллюзию, что нашей библиотекой можно пользоваться, не вникая в её внутреннее устройство.

Проект в целом, развивается активно. Появляются инструменты для управления инфраструктурой из сотен баз для тысяч пользователей, но инструментов для быстрого старта а-ля 1с, в планах нет.
