### ISSUE TITLE
Дискретный ряд для значений параметров

### ISSUE THREAD

**Issue by unpete** [oknosoft/metadata.js#441]
Нередко возникает потребность для допреквизита или параметра, имеющего числовой или строковый тип, задать фиксированный список значений.
Программисты в этом случае, часто создают перечислимое свойство или городят сложные модификаторы.
В первом случае, возникают лишние ссылки значений объектов и усложняется код из-за необходимости транслировать ссылки значений обратно в примитивный тип.
Во втором случае, лишний элемент справочника Формулы и трудносопровождаемый код.

Решено в табчасти умолчаний значений параметров, добавить реквизит, где программист или технолог смогут задать дискретный ряд значений для текущего параметра. Этот ряд может быть разным для разного контекста. Например, параметра `Ширина`, может иметь список `200, 300, 400` для вставки `Подоконник` и `20, 25, 30` для допвставки `Соединитель`

**Comment by unpete** [comment]
![image](https://user-images.githubusercontent.com/12096477/61624585-4dae9300-ac92-11e9-9513-56ceef324202.png)

**Comment by senitskiy** [comment]
Будет в деве, посмотрим, попробуем.
