### ISSUE TITLE
Документация по использованию библиотеки

### ISSUE THREAD

**Issue by gonzilac** [oknosoft/metadata.js#444]
Добрый день! Хотим использовать данную библиотеку в своем проекте, но нигде не получается найти информацию о том, как ей пользоваться. Не могли бы вы предоставить пошаговую инструкцию по использованию и примеры интеграции с внешними источниками (1С, реляционная СУБД)? Нигде не получилось найти внятной и актуальной документации по использованию данной библиотеки.

**Comment by unpete** [comment]
Есть [jsdoc](http://www.oknosoft.ru/upzp/apidocs/classes/DataObj.html) для старой версии и [helloworld](https://github.com/oknosoft/helloworld)
Актуальность первого и второго - так себе - на несколько лет отстало.
Если проект серьёзный, пишите на email, можем обсудить совместную работу.
