### ISSUE TITLE
Сторонние библиотеки в lib

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#81]
Почему сторонние библиотеки находятся в папке lib, а не в node_modules?

**Comment by unpete** [comment]
Для production, по возможности грузим библиотеки одним запросом к [jsdelivr](https://www.jsdelivr.com/)

Основной контекст metadata.js - браузер, не все сторонние библиотеки зарегистрированы в npm.
Если часть библиотек не поставляется в npm, не вижу ничего страшного в том, чтобы и остальные библиотеки лежали не в node_modules.

Еще, момент. Иногда есть необходимость внести изменения в стороннюю библиотеку. Pull-request разработчик может отклонить или рассматривать слишком долго. В этом случае - правим свой fork, а результат помещаем в lib
