### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#82]
Планируете ли вы переход на Typescript или использование es6, es7 с babel и webpack для улучшения кода?

**Comment by unpete** [comment]
Использования Typescript в планах нет.
При написании кода, ориентируемся на браузеры Chrome, FF и EDGE.
Используем в коде возможности, es6, es7, которые эти браузеры поддерживают.
Для сборки используем Galp.
Аргументов в пользу перехода на babel и webpack пока не вижу.

**Comment by unpete** [comment]
Metadata.js предоставляет разработчику высокоуровневую объектную модель со ссылочной типизацией.
Описание типов DataObj выполняется на стороне 1С или обычном текстовом редакторе, но метаданные - это некий внешний объект, на основании которого metadata строит справочники, документы, регистры и т.д.

Типизация полей DataObj у нас достаточно строгая безо всякого Typescript.
Притянуть за уши typescript в metadata.js можно, но это как запрягать лошадь в гоночный автомобиль.

**Comment by kodermax** [comment]
От тупоскрипта взять namespace, классы  и некое ооп, а то кода с одними функциями отбавляй.

**Comment by unpete** [comment]
Пример, пожалуйста.
В metadata, действительно, много неаккуратного кода, но с namespace, классами и наследованием, как раз, всё в порядке. Пример:
Есть абстрактный класс `DataObj`, у него есть наследник `RefDataObj` - всё еще абстрактный.
У `RefDataObj` есть наследники `CatObj` - справочник, `DocObj` - документ и т.д.
