### ISSUE TITLE
Инспектор кода и ReactJs

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#83]
Проекту также не хватает здесь travel ci подобных систем, проверки кода, написание кода по выбранному стандарту и ReactJs)

**Comment by unpete** [comment]
С благодарностью приму pull-request с реализацией перечисленного функционала или хотя бы - wbs план-график мероприятий.

По ReactJs, просьба сформулировать предложение более внятно: какую именно функциональность предлагаете перевести в термины react?

**Comment by kodermax** [comment]
Можно я пульну eslint и webpack, он все таки попроще по понятнее?

**Comment by unpete** [comment]
> Можно я пульну eslint и webpack

Лучше проблему словами опишите. Что именно не нравится или не получается сделать.
Возможно, вы пытаетесь проломить стену, в то время, когда можно взять ключ и открыть дверь.

**Comment by kodermax** [comment]
Посмотрел gulp, это какой-то ужас, вы его как-то сторонние библиотеки странно используете, кусками, что ли, почему нет нормального подключения, одной строчкой, это хоз-во потом сложно будет поддерживать менять постоянно придется, почему так сделано?

**Comment by kodermax** [comment]
Идея такая, что работали команды npm install, npm update, npm start, npm run build без бубнов
