### ISSUE TITLE
Интерфейсы для клиента

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#90]
А интерфейсы быстро рисуются для клиента на яваскрипте к примеру,
заявку на покупку.

**Comment by unpete** [comment]
- Есть автоформы - их вообще рисовать не надо. Строятся автоматически, наподобие тех, что создаёт платформа 1С. В автоформах работает вся сылочная математика - поля выбора номенклатур, контрагентов и т.д. как в шапке, так и в табличных частях
- Есть формы, полностью нарисованные программистом, в них можно исползовать хитрые виджеты - хоть наши, хоть из сторонних библиотек
- Есть некий гибрид: в метаданных можно описать порядок и видимость полей шапки и табличных частей, система сформирует форму по расширенному описанию метаданных

**Comment by unpete** [comment]
Примеры автоформ есть в Codex - это формы вообще без кода. Для запуска служит кнопка _Выполнить_ на панели инструментов
[Форма списка и выбора](http://www.oknosoft.ru/metadata/codex/#obj=01121&ref=&frm=&view=js)
[Формы объектов](http://www.oknosoft.ru/metadata/codex/#obj=01122&ref=&frm=&view=js)
[Поле ввода OCombo](http://www.oknosoft.ru/metadata/codex/#obj=0116&ref=&frm=&view=js)
[Таблица реквизитов шапки](http://www.oknosoft.ru/metadata/codex/#obj=0117&ref=&frm=&view=js)
[Табличная часть](http://www.oknosoft.ru/metadata/codex/#obj=0118&ref=&frm=&view=js)
