### ISSUE TITLE
dhtml вы что-то правите

### ISSUE THREAD

**Issue by kodermax** [oknosoft/metadata.js#95]
ВЫ в сторонний модуль dhtml, свои правки тоже вносите?

**Comment by unpete** [comment]
Не от хорошей жизни.
Если бы dhtmlx был открытым проектом и принимал pull requests, изменения можно было бы оформлять на их стороне. Но приходится на нашей.
Вообще, зависимость от dhtmlx не очень сильная. Есть [metadata.core.js](https://github.com/oknosoft/metadata.js/blob/master/lib/metadata.core.js) без визуальных компонентов - голая математика, но на реальных проектах без доработанного dhtmlx пока не обойтись.

**Comment by kodermax** [comment]
Может сделать тогда свой fork для dhtml туда вносить правки + апдейты автора сливать в этот форк, тогда получится красивое подключение библиотеки в этот проект?

**Comment by unpete** [comment]
Задача красивого подключения UI, наверное, важна, но сейчас она имеет низкий приоритет на фоне нерешенных задач обработки данных.
